### ISSUE TITLE
Can you please make a heavier work load for AVX, AVX2 and AVX3 

### ISSUE THREAD

**Issue by jcreyesintel** [VictorRodriguez/avx_bench#2]
Can you please make this summary of workloads for our testing with OS content  under  Clear Linux ?
this would enable us, to  stress out threads with a heavier load  with different instructions AVX, so we can catch a heavier voltage droop  on a validation system, triggering with a GPIO
AVX  DIV_AVX, ADD_AVX y MUL_AVX 
AVX2  DIV_AVX2, ADD_AVX2 y MUL_AVX2 
AVX3  DIV_AVX3, ADD_AVX3 y MUL_AVX3 
with parameters of **loops** and **delay** in order to control work cycle / frequency during stress

**Comment by VictorRodriguez** [comment]
@jcreyesintel Pre-release 0.1 fix this for you ?

**Comment by jcreyesintel** [comment]
Thx Victor, we can close this request, as it enabled us for the moment what we want to accomplish. if there is needed something else we can open another ticket.

**Comment by VictorRodriguez** [comment]
Thanks :) Feel free to open as many tickets as you want , happy to help
