### ISSUE TITLE
Pass\Fail flagging 

### ISSUE THREAD

**Issue by vchowd** [VictorRodriguez/avx_bench#3]
Can you please clearly indicate a pass or fail condition at the end of the test run.

Thanks

**Comment by VictorRodriguez** [comment]
Hi @vchowd thanks for your request , is this a valid output for you 

$ ./stress_add_avx2 -l 1000 -d 1000
PASS: Benchmark completed
Loops: 1000
Delay per function: 0.001 in seconds
Total time: <X> seconds to execute
foo() took <Y> seconds in avg to execute

Where X is total time took the math function  to execute over the number of loops and Y is the average time took the math function ( add for example ) to execute

**Comment by VictorRodriguez** [comment]
This is with the clean up of code : 
https://github.com/VictorRodriguez/avx_bench/commit/336ed65b5b1676980339a506e56f5d416a8ff2b0

**Comment by vchowd** [comment]
Looks good!
thanks
