### ISSUE TITLE
Stress test improvement

### ISSUE THREAD

**Issue by vchowd** [VictorRodriguez/avx_bench#4]
Can the test be improved to increase overall stress by changing the data space to include addition of very large numbers (instead of current 1 + 2).

Thanks

**Comment by VictorRodriguez** [comment]
with the commit : 
https://github.com/VictorRodriguez/avx_bench/commit/430cd892a66e4a725ccd8a977dbb2f21f31e0cb0
 
is possible to accept external values , if no external value is provided the test by itself generate a random number with 

x_value = 1000 * (float)rand()/RAND_MAX;

Example: 

$ ./stress_add_avx2 -l 1000 -d 1000 -x 1000000.123 -y 2000000.123
PASS: Benchmark completed
Loops: 1000
Delay per function: 0.001 in seconds
Total time:<> seconds to execute
foo() took  <> seconds in avg to execute
Operator1: 1000000.125000
Operator2: 2000000.125000
Result: 3000000.250000

**Comment by VictorRodriguez** [comment]
@vchowd let me know if this is what you are looking for , if so I can replicate for other tests, right now is just for stress_add_avx2

**Comment by vchowd** [comment]
Can you please enhance all of the other tests to include larger numbers depending on their data type.

thanks
Vikram
